#!/bin/bash

files="index.html
sonic.wav
../main.c
soundstretch.wav
Sonic-NDK.apk"

markdown_py index.md > index.html
if [ -f ../version ]; then
    version=`awk '{print $1}' ../version`
    sourceTarball=../../$version.orig.tar.gz
    if [ -f $sourceTarball ]; then
	destTarball=$version.tar.gz
	scp $sourceTarball root@dev.vinux-project.org:/var/www/dev.vinux-project.org/sonic/download/$destTarball
    fi
fi
flac -d sonic.flac soundstretch.flac
scp $files root@dev.vinux-project.org:/var/www/dev.vinux-project.org/sonic
rm *.wav index.html
